/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tvapi);
  }
}(this, function(expect, Tvapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Tvapi.CollectsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CollectsApi', function() {
    describe('collectsDelete', function() {
      it('should call collectsDelete successfully', function(done) {
        //uncomment below and update the code to test collectsDelete
        //instance.collectsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectsGet', function() {
      it('should call collectsGet successfully', function(done) {
        //uncomment below and update the code to test collectsGet
        //instance.collectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectsIdDelete', function() {
      it('should call collectsIdDelete successfully', function(done) {
        //uncomment below and update the code to test collectsIdDelete
        //instance.collectsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectsIdGet', function() {
      it('should call collectsIdGet successfully', function(done) {
        //uncomment below and update the code to test collectsIdGet
        //instance.collectsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectsIdPut', function() {
      it('should call collectsIdPut successfully', function(done) {
        //uncomment below and update the code to test collectsIdPut
        //instance.collectsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectsPost', function() {
      it('should call collectsPost successfully', function(done) {
        //uncomment below and update the code to test collectsPost
        //instance.collectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
