/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CommonResponse model module.
* @module model/CommonResponse
* @version 3.0
*/
export default class CommonResponse {
    /**
    * Constructs a new <code>CommonResponse</code>.
    * @alias module:model/CommonResponse
    * @class
    * @param code {Number} 
    * @param message {String} 
    */

    constructor(code, message) {
        

        
        

        this['code'] = code;this['message'] = message;

        
    }

    /**
    * Constructs a <code>CommonResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CommonResponse} obj Optional instance to populate.
    * @return {module:model/CommonResponse} The populated <code>CommonResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommonResponse();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    code = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {Object} data
    */
    data = undefined;








}


