/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Event model module.
* @module model/Event
* @version 3.0
*/
export default class Event {
    /**
    * Constructs a new <code>Event</code>.
    * event
    * @alias module:model/Event
    * @class
    * @param eventId {String} eventId
    * @param mac {String} mac
    */

    constructor(eventId, mac) {
        

        
        

        this['eventId'] = eventId;this['mac'] = mac;

        
    }

    /**
    * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Event} obj Optional instance to populate.
    * @return {module:model/Event} The populated <code>Event</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Event();

            
            
            

            if (data.hasOwnProperty('eventId')) {
                obj['eventId'] = ApiClient.convertToType(data['eventId'], 'String');
            }
            if (data.hasOwnProperty('mac')) {
                obj['mac'] = ApiClient.convertToType(data['mac'], 'String');
            }
            if (data.hasOwnProperty('extraParameter')) {
                obj['extraParameter'] = ApiClient.convertToType(data['extraParameter'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('app')) {
                obj['app'] = ApiClient.convertToType(data['app'], 'String');
            }
            if (data.hasOwnProperty('versionName')) {
                obj['versionName'] = ApiClient.convertToType(data['versionName'], 'String');
            }
        }
        return obj;
    }

    /**
    * eventId
    * @member {String} eventId
    */
    eventId = undefined;
    /**
    * mac
    * @member {String} mac
    */
    mac = undefined;
    /**
    * extraParameter json format
    * @member {String} extraParameter
    */
    extraParameter = undefined;
    /**
    * channel
    * @member {String} channel
    */
    channel = undefined;
    /**
    * app
    * @member {String} app
    */
    app = undefined;
    /**
    * versionName
    * @member {String} versionName
    */
    versionName = undefined;








}


