/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EventDetail model module.
* @module model/EventDetail
* @version 3.0
*/
export default class EventDetail {
    /**
    * Constructs a new <code>EventDetail</code>.
    * EventDetail
    * @alias module:model/EventDetail
    * @class
    * @param messageDate {String} 
    * @param messageNum {Number} 
    * @param userNum {Number} 
    */

    constructor(messageDate, messageNum, userNum) {
        

        
        

        this['messageDate'] = messageDate;this['messageNum'] = messageNum;this['userNum'] = userNum;

        
    }

    /**
    * Constructs a <code>EventDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EventDetail} obj Optional instance to populate.
    * @return {module:model/EventDetail} The populated <code>EventDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventDetail();

            
            
            

            if (data.hasOwnProperty('messageDate')) {
                obj['messageDate'] = ApiClient.convertToType(data['messageDate'], 'String');
            }
            if (data.hasOwnProperty('messageNum')) {
                obj['messageNum'] = ApiClient.convertToType(data['messageNum'], 'Number');
            }
            if (data.hasOwnProperty('userNum')) {
                obj['userNum'] = ApiClient.convertToType(data['userNum'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} messageDate
    */
    messageDate = undefined;
    /**
    * @member {Number} messageNum
    */
    messageNum = undefined;
    /**
    * @member {Number} userNum
    */
    userNum = undefined;








}


