/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EventExtraParameterDetail model module.
* @module model/EventExtraParameterDetail
* @version 3.0
*/
export default class EventExtraParameterDetail {
    /**
    * Constructs a new <code>EventExtraParameterDetail</code>.
    * EventExtraParameterDetail
    * @alias module:model/EventExtraParameterDetail
    * @class
    * @param parameter {String} 
    * @param messageNum {Number} 
    */

    constructor(parameter, messageNum) {
        

        
        

        this['parameter'] = parameter;this['messageNum'] = messageNum;

        
    }

    /**
    * Constructs a <code>EventExtraParameterDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EventExtraParameterDetail} obj Optional instance to populate.
    * @return {module:model/EventExtraParameterDetail} The populated <code>EventExtraParameterDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventExtraParameterDetail();

            
            
            

            if (data.hasOwnProperty('parameter')) {
                obj['parameter'] = ApiClient.convertToType(data['parameter'], 'String');
            }
            if (data.hasOwnProperty('messageNum')) {
                obj['messageNum'] = ApiClient.convertToType(data['messageNum'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} parameter
    */
    parameter = undefined;
    /**
    * @member {Number} messageNum
    */
    messageNum = undefined;








}


