/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Font model module.
* @module model/Font
* @version 3.0
*/
export default class Font {
    /**
    * Constructs a new <code>Font</code>.
    * font
    * @alias module:model/Font
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Font</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Font} obj Optional instance to populate.
    * @return {module:model/Font} The populated <code>Font</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Font();

            
            
            

            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('font')) {
                obj['font'] = ApiClient.convertToType(data['font'], 'String');
            }
            if (data.hasOwnProperty('fontSize')) {
                obj['fontSize'] = ApiClient.convertToType(data['fontSize'], 'Number');
            }
        }
        return obj;
    }

    /**
    * color
    * @member {String} color
    */
    color = undefined;
    /**
    * font
    * @member {String} font
    */
    font = undefined;
    /**
    * size
    * @member {Number} fontSize
    */
    fontSize = undefined;








}


