/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Game model module.
* @module model/Game
* @version 3.0
*/
export default class Game {
    /**
    * Constructs a new <code>Game</code>.
    * game
    * @alias module:model/Game
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Game</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Game} obj Optional instance to populate.
    * @return {module:model/Game} The populated <code>Game</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Game();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('package_name')) {
                obj['package_name'] = ApiClient.convertToType(data['package_name'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('background')) {
                obj['background'] = ApiClient.convertToType(data['background'], 'String');
            }
            if (data.hasOwnProperty('poster')) {
                obj['poster'] = ApiClient.convertToType(data['poster'], 'String');
            }
            if (data.hasOwnProperty('screenshot')) {
                obj['screenshot'] = ApiClient.convertToType(data['screenshot'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('interaction_type')) {
                obj['interaction_type'] = ApiClient.convertToType(data['interaction_type'], 'String');
            }
            if (data.hasOwnProperty('developer')) {
                obj['developer'] = ApiClient.convertToType(data['developer'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('keyword')) {
                obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('update_time')) {
                obj['update_time'] = ApiClient.convertToType(data['update_time'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} package_name
    */
    package_name = undefined;
    /**
    * @member {String} icon
    */
    icon = undefined;
    /**
    * @member {String} background
    */
    background = undefined;
    /**
    * @member {String} poster
    */
    poster = undefined;
    /**
    * @member {String} screenshot
    */
    screenshot = undefined;
    /**
    * @member {String} summary
    */
    summary = undefined;
    /**
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {String} version
    */
    version = undefined;
    /**
    * @member {String} interaction_type
    */
    interaction_type = undefined;
    /**
    * @member {String} developer
    */
    developer = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {String} keyword
    */
    keyword = undefined;
    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {Number} score
    */
    score = undefined;
    /**
    * @member {String} download_url
    */
    download_url = undefined;
    /**
    * @member {String} language
    */
    language = undefined;
    /**
    * @member {String} update_time
    */
    update_time = undefined;








}


