/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Login model module.
* @module model/Login
* @version 3.0
*/
export default class Login {
    /**
    * Constructs a new <code>Login</code>.
    * @alias module:model/Login
    * @class
    * @param name {String} 
    * @param password {String} 
    */

    constructor(name, password) {
        

        
        

        this['name'] = name;this['password'] = password;

        
    }

    /**
    * Constructs a <code>Login</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Login} obj Optional instance to populate.
    * @return {module:model/Login} The populated <code>Login</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Login();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} password
    */
    password = undefined;








}


