/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Movie model module.
* @module model/Movie
* @version 3.0
*/
export default class Movie {
    /**
    * Constructs a new <code>Movie</code>.
    * a movie
    * @alias module:model/Movie
    * @class
    * @param duration {Number} 
    * @param episode {Number} 
    * @param images {String} 
    * @param name {String} 
    * @param price {Number} 
    * @param summary {String} 
    * @param frameRatio {Number} 
    * @param size {Number} 
    * @param ext {String} 
    */

    constructor(duration, episode, images, name, price, summary, frameRatio, size, ext) {
        

        
        

        this['duration'] = duration;this['episode'] = episode;this['images'] = images;this['name'] = name;this['price'] = price;this['summary'] = summary;this['frame_ratio'] = frameRatio;this['size'] = size;this['ext'] = ext;

        
    }

    /**
    * Constructs a <code>Movie</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Movie} obj Optional instance to populate.
    * @return {module:model/Movie} The populated <code>Movie</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Movie();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('episode')) {
                obj['episode'] = ApiClient.convertToType(data['episode'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], 'String');
            }
            if (data.hasOwnProperty('movie_id')) {
                obj['movie_id'] = ApiClient.convertToType(data['movie_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('program_id')) {
                obj['program_id'] = ApiClient.convertToType(data['program_id'], 'String');
            }
            if (data.hasOwnProperty('series_id')) {
                obj['series_id'] = ApiClient.convertToType(data['series_id'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('frame_ratio')) {
                obj['frame_ratio'] = ApiClient.convertToType(data['frame_ratio'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('ext')) {
                obj['ext'] = ApiClient.convertToType(data['ext'], 'String');
            }
            if (data.hasOwnProperty('background_url')) {
                obj['background_url'] = ApiClient.convertToType(data['background_url'], 'String');
            }
            if (data.hasOwnProperty('cover_url')) {
                obj['cover_url'] = ApiClient.convertToType(data['cover_url'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} duration
    */
    duration = undefined;
    /**
    * @member {Number} episode
    */
    episode = undefined;
    /**
    * @member {String} images
    */
    images = undefined;
    /**
    * @member {String} movie_id
    */
    movie_id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Number} price
    */
    price = undefined;
    /**
    * @member {String} program_id
    */
    program_id = undefined;
    /**
    * @member {String} series_id
    */
    series_id = undefined;
    /**
    * @member {String} summary
    */
    summary = undefined;
    /**
    * @member {Number} frame_ratio
    */
    frame_ratio = undefined;
    /**
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {String} ext
    */
    ext = undefined;
    /**
    * @member {String} background_url
    */
    background_url = undefined;
    /**
    * @member {String} cover_url
    */
    cover_url = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;








}


