/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PageSection from './PageSection';





/**
* The PageContent model module.
* @module model/PageContent
* @version 3.0
*/
export default class PageContent {
    /**
    * Constructs a new <code>PageContent</code>.
    * a page
    * @alias module:model/PageContent
    * @class
    * @param name {String} page name
    * @param sectionList {Array.<module:model/PageSection>} page sectionList
    */

    constructor(name, sectionList) {
        

        
        

        this['name'] = name;this['sectionList'] = sectionList;

        
    }

    /**
    * Constructs a <code>PageContent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PageContent} obj Optional instance to populate.
    * @return {module:model/PageContent} The populated <code>PageContent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageContent();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('background')) {
                obj['background'] = ApiClient.convertToType(data['background'], 'String');
            }
            if (data.hasOwnProperty('sectionList')) {
                obj['sectionList'] = ApiClient.convertToType(data['sectionList'], [PageSection]);
            }
        }
        return obj;
    }

    /**
    * page name
    * @member {String} name
    */
    name = undefined;
    /**
    * page id
    * @member {String} background
    */
    background = undefined;
    /**
    * page sectionList
    * @member {Array.<module:model/PageSection>} sectionList
    */
    sectionList = undefined;








}


