/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PageCellSpecialIcon model module.
* @module model/PageCellSpecialIcon
* @version 3.0
*/
export default class PageCellSpecialIcon {
    /**
    * Constructs a new <code>PageCellSpecialIcon</code>.
    * specialIcon
    * @alias module:model/PageCellSpecialIcon
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PageCellSpecialIcon</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PageCellSpecialIcon} obj Optional instance to populate.
    * @return {module:model/PageCellSpecialIcon} The populated <code>PageCellSpecialIcon</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageCellSpecialIcon();

            
            
            

            if (data.hasOwnProperty('anchor')) {
                obj['anchor'] = ApiClient.convertToType(data['anchor'], 'String');
            }
            if (data.hasOwnProperty('cover')) {
                obj['cover'] = ApiClient.convertToType(data['cover'], 'String');
            }
            if (data.hasOwnProperty('h')) {
                obj['h'] = ApiClient.convertToType(data['h'], 'Number');
            }
            if (data.hasOwnProperty('w')) {
                obj['w'] = ApiClient.convertToType(data['w'], 'Number');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} anchor
    */
    anchor = undefined;
    /**
    * cover
    * @member {String} cover
    */
    cover = undefined;
    /**
    * @member {Number} h
    */
    h = undefined;
    /**
    * @member {Number} w
    */
    w = undefined;
    /**
    * @member {Number} x
    */
    x = undefined;
    /**
    * @member {Number} y
    */
    y = undefined;








}


