/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PageCellSpecialIcon from './PageCellSpecialIcon';





/**
* The PageCell model module.
* @module model/PageCell
* @version 3.0
*/
export default class PageCell {
    /**
    * Constructs a new <code>PageCell</code>.
    * a cell
    * @alias module:model/PageCell
    * @class
    * @param cover {String} cell img
    * @param route {String} next page uri
    */

    constructor(cover, route) {
        

        
        

        this['cover'] = cover;this['route'] = route;

        
    }

    /**
    * Constructs a <code>PageCell</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PageCell} obj Optional instance to populate.
    * @return {module:model/PageCell} The populated <code>PageCell</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageCell();

            
            
            

            if (data.hasOwnProperty('activeBox')) {
                obj['activeBox'] = ApiClient.convertToType(data['activeBox'], 'Boolean');
            }
            if (data.hasOwnProperty('activeCover')) {
                obj['activeCover'] = ApiClient.convertToType(data['activeCover'], 'String');
            }
            if (data.hasOwnProperty('cover')) {
                obj['cover'] = ApiClient.convertToType(data['cover'], 'String');
            }
            if (data.hasOwnProperty('route')) {
                obj['route'] = ApiClient.convertToType(data['route'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('specialIcon')) {
                obj['specialIcon'] = PageCellSpecialIcon.constructFromObject(data['specialIcon']);
            }
        }
        return obj;
    }

    /**
    * activeBox
    * @member {Boolean} activeBox
    */
    activeBox = undefined;
    /**
    * activeCover
    * @member {String} activeCover
    */
    activeCover = undefined;
    /**
    * cell img
    * @member {String} cover
    */
    cover = undefined;
    /**
    * next page uri
    * @member {String} route
    */
    route = undefined;
    /**
    * name
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/PageCellSpecialIcon} specialIcon
    */
    specialIcon = undefined;








}


