/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PageContent from './PageContent';





/**
* The Page model module.
* @module model/Page
* @version 3.0
*/
export default class Page {
    /**
    * Constructs a new <code>Page</code>.
    * a page
    * @alias module:model/Page
    * @class
    * @param name {String} name must be unique
    * @param version {Number} version
    * @param content {module:model/PageContent} content
    * @param type {String} type
    * @param hasTop {Boolean} 
    */

    constructor(name, version, content, type, hasTop) {
        

        
        

        this['name'] = name;this['version'] = version;this['content'] = content;this['type'] = type;this['has_top'] = hasTop;

        
    }

    /**
    * Constructs a <code>Page</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Page} obj Optional instance to populate.
    * @return {module:model/Page} The populated <code>Page</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Page();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = PageContent.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('has_top')) {
                obj['has_top'] = ApiClient.convertToType(data['has_top'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * name must be unique
    * @member {String} name
    */
    name = undefined;
    /**
    * version
    * @member {Number} version
    */
    version = undefined;
    /**
    * content
    * @member {module:model/PageContent} content
    */
    content = undefined;
    /**
    * type
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {Boolean} has_top
    */
    has_top = undefined;








}


