/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SearchRecommend model module.
* @module model/SearchRecommend
* @version 3.0
*/
export default class SearchRecommend {
    /**
    * Constructs a new <code>SearchRecommend</code>.
    * a searchRecommend
    * @alias module:model/SearchRecommend
    * @class
    * @param seriesId {Number} 剧集id
    * @param app {String} 所属应用
    */

    constructor(seriesId, app) {
        

        
        

        this['series_id'] = seriesId;this['app'] = app;

        
    }

    /**
    * Constructs a <code>SearchRecommend</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SearchRecommend} obj Optional instance to populate.
    * @return {module:model/SearchRecommend} The populated <code>SearchRecommend</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchRecommend();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('series_id')) {
                obj['series_id'] = ApiClient.convertToType(data['series_id'], 'Number');
            }
            if (data.hasOwnProperty('cover_url')) {
                obj['cover_url'] = ApiClient.convertToType(data['cover_url'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('app')) {
                obj['app'] = ApiClient.convertToType(data['app'], 'String');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * 剧集id
    * @member {Number} series_id
    */
    series_id = undefined;
    /**
    * 图片
    * @member {String} cover_url
    */
    cover_url = undefined;
    /**
    * 名称
    * @member {String} name
    */
    name = undefined;
    /**
    * 所属应用
    * @member {String} app
    */
    app = undefined;








}


