/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Series model module.
* @module model/Series
* @version 3.0
*/
export default class Series {
    /**
    * Constructs a new <code>Series</code>.
    * a series
    * @alias module:model/Series
    * @class
    * @param actor {String} 
    * @param channel {String} 
    * @param comment {String} 
    * @param director {String} 
    * @param endTime {String} 
    * @param episodes {Number} 
    * @param images {String} 
    * @param keyword {String} 
    * @param language {String} 
    * @param name {String} 
    * @param origin {String} 
    * @param price {Number} 
    * @param provider {String} 
    * @param score {Number} 
    * @param startTime {String} 
    * @param style {String} 
    * @param subtitle {String} 
    * @param summary {String} 
    * @param tag {String} 
    * @param type {String} 
    * @param year {String} 
    * @param backgroundUrl {String} 
    * @param coverUrl {String} 
    * @param categoryId {Number} 
    * @param firstLetter {String} 
    */

    constructor(actor, channel, comment, director, endTime, episodes, images, keyword, language, name, origin, price, provider, score, startTime, style, subtitle, summary, tag, type, year, backgroundUrl, coverUrl, categoryId, firstLetter) {
        

        
        

        this['actor'] = actor;this['channel'] = channel;this['comment'] = comment;this['director'] = director;this['end_time'] = endTime;this['episodes'] = episodes;this['images'] = images;this['keyword'] = keyword;this['language'] = language;this['name'] = name;this['origin'] = origin;this['price'] = price;this['provider'] = provider;this['score'] = score;this['start_time'] = startTime;this['style'] = style;this['subtitle'] = subtitle;this['summary'] = summary;this['tag'] = tag;this['type'] = type;this['year'] = year;this['background_url'] = backgroundUrl;this['cover_url'] = coverUrl;this['category_id'] = categoryId;this['first_letter'] = firstLetter;

        
    }

    /**
    * Constructs a <code>Series</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Series} obj Optional instance to populate.
    * @return {module:model/Series} The populated <code>Series</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Series();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('actor')) {
                obj['actor'] = ApiClient.convertToType(data['actor'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('director')) {
                obj['director'] = ApiClient.convertToType(data['director'], 'String');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'String');
            }
            if (data.hasOwnProperty('episodes')) {
                obj['episodes'] = ApiClient.convertToType(data['episodes'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], 'String');
            }
            if (data.hasOwnProperty('keyword')) {
                obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('series_id')) {
                obj['series_id'] = ApiClient.convertToType(data['series_id'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
            }
            if (data.hasOwnProperty('style')) {
                obj['style'] = ApiClient.convertToType(data['style'], 'String');
            }
            if (data.hasOwnProperty('subtitle')) {
                obj['subtitle'] = ApiClient.convertToType(data['subtitle'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'String');
            }
            if (data.hasOwnProperty('background_url')) {
                obj['background_url'] = ApiClient.convertToType(data['background_url'], 'String');
            }
            if (data.hasOwnProperty('cover_url')) {
                obj['cover_url'] = ApiClient.convertToType(data['cover_url'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'Number');
            }
            if (data.hasOwnProperty('category_name')) {
                obj['category_name'] = ApiClient.convertToType(data['category_name'], 'String');
            }
            if (data.hasOwnProperty('first_letter')) {
                obj['first_letter'] = ApiClient.convertToType(data['first_letter'], 'String');
            }
            if (data.hasOwnProperty('is_collect')) {
                obj['is_collect'] = ApiClient.convertToType(data['is_collect'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} actor
    */
    actor = undefined;
    /**
    * @member {String} channel
    */
    channel = undefined;
    /**
    * @member {String} comment
    */
    comment = undefined;
    /**
    * @member {String} director
    */
    director = undefined;
    /**
    * @member {String} end_time
    */
    end_time = undefined;
    /**
    * @member {Number} episodes
    */
    episodes = undefined;
    /**
    * @member {String} images
    */
    images = undefined;
    /**
    * @member {String} keyword
    */
    keyword = undefined;
    /**
    * @member {String} language
    */
    language = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} origin
    */
    origin = undefined;
    /**
    * @member {Number} price
    */
    price = undefined;
    /**
    * @member {String} provider
    */
    provider = undefined;
    /**
    * @member {Number} score
    */
    score = undefined;
    /**
    * @member {String} series_id
    */
    series_id = undefined;
    /**
    * @member {String} start_time
    */
    start_time = undefined;
    /**
    * @member {String} style
    */
    style = undefined;
    /**
    * @member {String} subtitle
    */
    subtitle = undefined;
    /**
    * @member {String} summary
    */
    summary = undefined;
    /**
    * @member {String} tag
    */
    tag = undefined;
    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {String} year
    */
    year = undefined;
    /**
    * @member {String} background_url
    */
    background_url = undefined;
    /**
    * @member {String} cover_url
    */
    cover_url = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {Number} category_id
    */
    category_id = undefined;
    /**
    * @member {String} category_name
    */
    category_name = undefined;
    /**
    * @member {String} first_letter
    */
    first_letter = undefined;
    /**
    * 是否收藏
    * @member {Boolean} is_collect
    */
    is_collect = undefined;








}


