/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Subject model module.
* @module model/Subject
* @version 3.0
*/
export default class Subject {
    /**
    * Constructs a new <code>Subject</code>.
    * a subject
    * @alias module:model/Subject
    * @class
    * @param type {Number} 专题类型 1是小小可爱那种模版，2是酷米那种模块
    * @param name {String} 专题名称
    * @param backgroundUrl {String} 背景图片
    * @param app {String} 所属应用
    */

    constructor(type, name, backgroundUrl, app) {
        

        
        

        this['type'] = type;this['name'] = name;this['background_url'] = backgroundUrl;this['app'] = app;

        
    }

    /**
    * Constructs a <code>Subject</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Subject} obj Optional instance to populate.
    * @return {module:model/Subject} The populated <code>Subject</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Subject();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('background_url')) {
                obj['background_url'] = ApiClient.convertToType(data['background_url'], 'String');
            }
            if (data.hasOwnProperty('app')) {
                obj['app'] = ApiClient.convertToType(data['app'], 'String');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * 专题类型 1是小小可爱那种模版，2是酷米那种模块
    * @member {Number} type
    */
    type = undefined;
    /**
    * 专题名称
    * @member {String} name
    */
    name = undefined;
    /**
    * 背景图片
    * @member {String} background_url
    */
    background_url = undefined;
    /**
    * 所属应用
    * @member {String} app
    */
    app = undefined;








}


