/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TemplateContent from './TemplateContent';





/**
* The Template model module.
* @module model/Template
* @version 3.0
*/
export default class Template {
    /**
    * Constructs a new <code>Template</code>.
    * a page
    * @alias module:model/Template
    * @class
    * @param name {String} name must be unique
    * @param content {module:model/TemplateContent} content
    */

    constructor(name, content) {
        

        
        

        this['name'] = name;this['content'] = content;

        
    }

    /**
    * Constructs a <code>Template</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Template} obj Optional instance to populate.
    * @return {module:model/Template} The populated <code>Template</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Template();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = TemplateContent.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }

    /**
    * id
    * @member {Number} id
    */
    id = undefined;
    /**
    * name must be unique
    * @member {String} name
    */
    name = undefined;
    /**
    * content
    * @member {module:model/TemplateContent} content
    */
    content = undefined;
    /**
    * status
    * @member {Number} status
    */
    status = undefined;








}


