/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The VideoShowNames model module.
* @module model/VideoShowNames
* @version 3.0
*/
export default class VideoShowNames {
    /**
    * Constructs a new <code>VideoShowNames</code>.
    * a video
    * @alias module:model/VideoShowNames
    * @class
    * @param names {Array.<String>} 
    * @param showNames {Array.<String>} 
    */

    constructor(names, showNames) {
        

        
        

        this['names'] = names;this['showNames'] = showNames;

        
    }

    /**
    * Constructs a <code>VideoShowNames</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VideoShowNames} obj Optional instance to populate.
    * @return {module:model/VideoShowNames} The populated <code>VideoShowNames</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoShowNames();

            
            
            

            if (data.hasOwnProperty('names')) {
                obj['names'] = ApiClient.convertToType(data['names'], ['String']);
            }
            if (data.hasOwnProperty('showNames')) {
                obj['showNames'] = ApiClient.convertToType(data['showNames'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} names
    */
    names = undefined;
    /**
    * @member {Array.<String>} showNames
    */
    showNames = undefined;








}


