/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The VideoNames model module.
* @module model/VideoNames
* @version 3.0
*/
export default class VideoNames {
    /**
    * Constructs a new <code>VideoNames</code>.
    * a video
    * @alias module:model/VideoNames
    * @class
    * @param names {Array.<String>} 
    */

    constructor(names) {
        

        
        

        this['names'] = names;

        
    }

    /**
    * Constructs a <code>VideoNames</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VideoNames} obj Optional instance to populate.
    * @return {module:model/VideoNames} The populated <code>VideoNames</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoNames();

            
            
            

            if (data.hasOwnProperty('names')) {
                obj['names'] = ApiClient.convertToType(data['names'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} names
    */
    names = undefined;








}


