/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tvapi);
  }
}(this, function(expect, Tvapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Tvapi.PageSection();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PageSection', function() {
    it('should create an instance of PageSection', function() {
      // uncomment below and update the code to test PageSection
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be.a(Tvapi.PageSection);
    });

    it('should have the property disable (base name: "disable")', function() {
      // uncomment below and update the code to test the property disable
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property offset (base name: "offset")', function() {
      // uncomment below and update the code to test the property offset
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property tid (base name: "tid")', function() {
      // uncomment below and update the code to test the property tid
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property contentFont (base name: "contentFont")', function() {
      // uncomment below and update the code to test the property contentFont
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property titleFont (base name: "titleFont")', function() {
      // uncomment below and update the code to test the property titleFont
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

    it('should have the property contentList (base name: "contentList")', function() {
      // uncomment below and update the code to test the property contentList
      //var instane = new Tvapi.PageSection();
      //expect(instance).to.be();
    });

  });

}));
