/**
 * tvapi
 * The TV Backend api v3.0
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommonResponse from '../model/CommonResponse';
import Error from '../model/Error';

/**
* PlayHistorys service.
* @module api/PlayHistorysApi
* @version 3.0
*/
export default class PlayHistorysApi {

    /**
    * Constructs a new PlayHistorysApi. 
    * @alias module:api/PlayHistorysApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * get playHistorys top_list.
     * get playHistorys top_list.
     * @param {String} app 
     * @param {Number} type 
     * @param {Number} limit 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CommonResponse} and HTTP response
     */
    playHistorysTopListGetWithHttpInfo(app, type, limit) {
      let postBody = null;

      // verify the required parameter 'app' is set
      if (app === undefined || app === null) {
        throw new Error("Missing the required parameter 'app' when calling playHistorysTopListGet");
      }

      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling playHistorysTopListGet");
      }

      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling playHistorysTopListGet");
      }


      let pathParams = {
      };
      let queryParams = {
        'app': app,
        'type': type,
        'limit': limit
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommonResponse;

      return this.apiClient.callApi(
        '/playHistorys/top_list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * get playHistorys top_list.
     * get playHistorys top_list.
     * @param {String} app 
     * @param {Number} type 
     * @param {Number} limit 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CommonResponse}
     */
    playHistorysTopListGet(app, type, limit) {
      return this.playHistorysTopListGetWithHttpInfo(app, type, limit)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
